<?php
/**
 * El Tronador — Advanced Cache Drop-in
 *
 * This file is automatically generated by El Tronador v{{ETR_VERSION}}.
 * It runs BEFORE WordPress loads to serve cached pages at maximum speed.
 *
 * DO NOT EDIT — changes will be overwritten on plugin activation.
 *
 * @package ElTronador
 */

if ( ! defined( 'ABSPATH' ) ) {
    return;
}

// Cache directory (injected at generation time).
$etr_cache_dir = '{{ETR_CACHE_DIR}}';

// Cache TTL: 10 hours (36000 seconds) — keeps Contact Form 7 nonces valid.
$etr_ttl = 36000;

// ---- Early-exit conditions ----

// Only serve cache for GET requests.
if ( 'GET' !== ( $_SERVER['REQUEST_METHOD'] ?? '' ) ) {
    return;
}

// Never serve cache to logged-in users.
if ( ! empty( $_COOKIE ) ) {
    foreach ( array_keys( $_COOKIE ) as $cookie_name ) {
        if ( str_starts_with( $cookie_name, 'wordpress_logged_in_' ) ) {
            return;
        }
    }
}

// Skip AJAX, WP-CLI, and REST API requests.
if (
    ( defined( 'DOING_AJAX' ) && DOING_AJAX ) ||
    ( defined( 'WP_CLI' ) && WP_CLI ) ||
    ( defined( 'REST_REQUEST' ) && REST_REQUEST )
) {
    return;
}

// Skip POST-back indicators.
if ( ! empty( $_POST ) ) {
    return;
}

// ---- Build cache file path ----

$etr_host = $_SERVER['HTTP_HOST'] ?? '';
$etr_uri  = $_SERVER['REQUEST_URI'] ?? '/';

// Sanitize host and URI for safe filesystem path.
$etr_host = preg_replace( '/[^a-zA-Z0-9._-]/', '', $etr_host );

// Strip query string for cache lookup.
$etr_path = strtok( $etr_uri, '?' );
$etr_path = rtrim( $etr_path, '/' );
$etr_path = $etr_path ?: '/';
$etr_path = preg_replace( '/[^a-zA-Z0-9\/._-]/', '', $etr_path );

// Skip WordPress admin, login, cron, API paths.
$etr_skip_paths = [ '/wp-admin', '/wp-login.php', '/wp-cron.php', '/xmlrpc.php', '/wp-json' ];
foreach ( $etr_skip_paths as $etr_skip ) {
    if ( str_starts_with( $etr_path, $etr_skip ) ) {
        return;
    }
}

// Skip WPS Hide Login custom URL (read from DB is not possible here, but
// the main plugin ensures this URL is never written to cache in the first place).

$etr_cache_file = $etr_cache_dir . $etr_host . $etr_path . '/index.html';

// ---- Serve from cache if valid ----

if ( file_exists( $etr_cache_file ) ) {
    $etr_age = time() - filemtime( $etr_cache_file );

    // Expired? Let WordPress handle the request and regenerate cache.
    if ( $etr_age > $etr_ttl ) {
        return;
    }

    // Serve the cached page.
    header( 'X-El-Tronador-Cache: HIT' );
    header( 'X-El-Tronador-Cache-Age: ' . $etr_age );
    readfile( $etr_cache_file );
    exit;
}

// Cache MISS — WordPress will handle the request normally,
// and the plugin's output buffer will write the cache file.
